import { ADA, AMARA, IFEOMA, KUNLE, RAVI, SAM, ZAINAB } from "@/pages/rooms/data";
import { DAVID, JOY, PETER } from "@/pages/digest/data";
import type {
  ChainDetail,
  ChainListRow,
  ClosedInsightCard,
  ClosedObligationRow,
  MyObligationRow,
  ObligationDetail,
  OverdueRow,
  OwedToMeRow,
} from "@/pages/handoff/types";

/**
 * Data for the /handoff rebuild — sourced from
 * flolyt-figma-designs/Everyday Screens/flolyt-handoff/ (H00–H16). People are
 * reused as-is from rooms/data.ts (ADA, RAVI, KUNLE, SAM, AMARA, ZAINAB,
 * IFEOMA) and digest/data.ts (PETER, JOY, DAVID — all Customer Success, the
 * same East Africa CS roster this export's names match exactly). H06 calls
 * Kunle "Kunle Ade"; kept as the existing first-name-only KUNLE record
 * (matching initials "KO" and department) rather than inventing a surname
 * conflict, same "SVG wins on content, roster wins on identity" call as
 * Today's Ravi Mehta/Ravi Menon note.
 */

export { ADA, RAVI, KUNLE, SAM, AMARA, ZAINAB, IFEOMA, PETER, JOY, DAVID };

/** H01 — wired but unreachable with the default below, same pattern as every prior rebuild's empty state. */
export const HANDOFF_EMPTY = false;

/** H02 — the chains index table. Only "delivery-fee" and "card-retry" get full detail builds (H04/H05/H06 and H14) — every other row falls back to a not-found state, the "one/two reference row" pattern used throughout this app. */
export const CHAIN_LIST: ChainListRow[] = [
  {
    id: "delivery-fee",
    title: "The delivery-fee release",
    startedTeam: "Engineering",
    startedDate: "4 Mar",
    teamsCount: 5,
    obligationsCount: 7,
    overdueCount: 1,
    oldestSignal: "161 days",
    oldestSignalTone: "rose",
    status: "live",
    statusLabel: "live",
    statusTone: "amber",
  },
  {
    id: "card-retry",
    title: "Card retry window",
    startedTeam: "Finance",
    startedDate: "28 Mar",
    teamsCount: 3,
    obligationsCount: 4,
    overdueCount: 0,
    oldestSignal: "28 days",
    status: "closed",
    statusLabel: "closed",
    statusTone: "teal",
  },
  {
    id: "lagos-delivery-failures",
    title: "Lagos delivery failures",
    startedTeam: "Support",
    startedDate: "11 Mar",
    teamsCount: 3,
    obligationsCount: 3,
    overdueCount: 0,
    oldestSignal: "41 days",
    status: "closed",
    statusLabel: "closed",
    statusTone: "teal",
  },
  {
    id: "discount-leakage",
    title: "Discount leakage",
    startedTeam: "Sales",
    startedDate: "2 Feb",
    teamsCount: 4,
    obligationsCount: 5,
    overdueCount: 1,
    oldestSignal: "94 days",
    oldestSignalTone: "amber",
    status: "live",
    statusLabel: "live",
    statusTone: "amber",
  },
  {
    id: "ghana-signup-drop",
    title: "Ghana signup drop",
    startedTeam: "Marketing",
    startedDate: "10 Aug",
    teamsCount: 2,
    obligationsCount: 0,
    overdueCount: 0,
    oldestSignal: "2 days",
    status: "no_owner",
    statusLabel: "No owner",
    statusTone: "amber",
  },
  {
    id: "weekend-push-fatigue",
    title: "Weekend push fatigue",
    startedTeam: "Marketing",
    startedDate: "3 Mar",
    teamsCount: 2,
    obligationsCount: 2,
    overdueCount: 0,
    oldestSignal: "Reopened",
    oldestSignalTone: "amber",
    status: "recovering",
    statusLabel: "recovering",
    statusTone: "ultra",
  },
];

/** H03 — "You owe" table (`/handoff?owner=me`). */
export const MY_OBLIGATIONS: MyObligationRow[] = [
  {
    id: "renewal-reforecast",
    chainId: "delivery-fee",
    title: "Re-forecast the August renewal book",
    toTeam: "Finance",
    fromChain: "Second order never happened",
    due: "9 Aug",
    dueTone: "rose",
    state: "4 days overdue",
    stateTone: "rose",
    blocks: "₦88M forecast",
    blocksTone: "rose",
    accepted: "you · 2 Aug",
  },
  {
    id: "kenya-holdout",
    chainId: "kenya-fee-rollback",
    title: "Confirm the Kenya holdout size",
    toTeam: "Product",
    fromChain: "Kenya fee rollback",
    due: "20 Aug",
    state: "not started",
    stateTone: "amber",
    blocks: "a measurement",
    blocksTone: "amber",
    accepted: "you · 11 Aug",
  },
  {
    id: "ghana-owner",
    chainId: "ghana-signup-drop",
    title: "Name a Ghana owner for Q4 planning",
    toTeam: "Customer Success",
    fromChain: "Ghana signup drop",
    due: "1 Sep",
    state: "in progress",
    stateTone: "ultra",
    blocks: "nothing yet",
    accepted: "you · 10 Aug",
  },
];

/** H03 — "Owed to you" table. */
export const OWED_TO_ME: OwedToMeRow[] = [
  {
    id: "instrument-fee-shown",
    title: "Instrument checkout.fee_shown",
    fromTeam: "Engineering",
    due: "14 Aug",
    state: "in progress",
    stateTone: "ultra",
    unlocks: "Measuring whether the fee fix worked",
  },
  {
    id: "reclassify-wismo",
    title: 'Reclassify "where is my order"',
    fromTeam: "Support",
    due: "done",
    state: "done · 4 Aug",
    stateTone: "teal",
    unlocks: "Support volume reads as a revenue signal",
  },
];

/** H10 — Overdue table (`/handoff?state=overdue`). `chainId` is only set where H12's own Engineering table names the originating chain — left unset rather than guessed elsewhere. */
export const OVERDUE_ROWS: OverdueRow[] = [
  {
    id: "order-lines-feed",
    chainId: "discount-leakage",
    title: "Add order_lines to the orders feed",
    team: "Engineering",
    owner: SAM,
    due: "28 Jul",
    daysOver: 41,
    blocks: "6 figures, 4 stages",
    blocksTone: "rose",
    escalatedTo: "Ada · day 7",
    escalatedToTone: "amber",
  },
  {
    id: "instrument-loyalty-tier",
    title: "Instrument loyalty.tier_shown",
    team: "Engineering",
    owner: SAM,
    due: "2 Aug",
    daysOver: 34,
    blocks: "1 feature invisible",
    blocksTone: "amber",
    escalatedTo: "Ada · day 7",
    escalatedToTone: "amber",
  },
  {
    id: "instrument-tier-shown-advocate",
    title: "Instrument tier_shown for Advocate",
    team: "Engineering",
    due: "2 Aug",
    daysOver: 34,
    blocks: "referral attribution",
    blocksTone: "amber",
    escalatedTo: "nobody",
    escalatedToTone: "rose",
  },
  {
    id: "lagos-address-autocomplete",
    chainId: "lagos-delivery-failures",
    title: "Fix the Lagos address autocomplete",
    team: "Engineering",
    owner: SAM,
    due: "9 Aug",
    daysOver: 15,
    blocks: "₦3.1M",
    escalatedTo: "team lead · day 7",
    escalatedToTone: "amber",
  },
  {
    id: "renewal-reforecast",
    chainId: "delivery-fee",
    title: "Re-forecast the August renewal book",
    team: "Customer Success",
    owner: KUNLE,
    due: "9 Aug",
    daysOver: 4,
    blocks: "₦88M forecast",
    blocksTone: "rose",
    escalatedTo: "Ada · today",
    escalatedToTone: "amber",
  },
  {
    id: "ghana-retry-rollout",
    title: "Roll the retry fix out to Ghana",
    team: "Finance",
    due: "2 Apr",
    daysOver: 134,
    blocks: "GHS 890k",
    blocksTone: "rose",
    escalatedTo: "nobody",
    escalatedToTone: "rose",
  },
];

const closedInsightsForCardRetry: ClosedInsightCard[] = [
  {
    eyebrow: "EVERY OBLIGATION WAS ACCEPTED SAME-DAY",
    title: "Median 2.5 hours",
    body: "Against a median of 3.2 hours on the delivery-fee chain — but with zero unaccepted. It is the unaccepted ones that rot, not the slow ones.",
    footnote: "4 of 4 accepted",
    footnoteTone: "teal",
  },
  {
    eyebrow: "EVERY ONE WAS A TASK",
    title: "Not a process change",
    body: "Move a window, approve a change, reclassify a driver, update a number. Each was inside one team's authority. Nothing needed somebody above the teams to decide it first.",
    footnote: "no cross-team ambiguity",
    footnoteTone: "teal",
  },
  {
    eyebrow: "THE MEASUREMENT WAS DESIGNED IN",
    title: "A 10% holdout from day one",
    body: 'Which is why this closed with ₦62M rather than "it probably helped". Chains that end in a number get cited; chains that end in an impression get re-argued.',
    footnote: "cited in two rooms since",
    footnoteTone: "teal",
  },
];

const closedObligationsForCardRetry: ClosedObligationRow[] = [
  {
    id: "retry-window",
    title: "Move the retry window to 09:00 local",
    team: "Engineering",
    owner: SAM,
    accepted: "28 Mar · 2 hrs",
    acceptedTone: "teal",
    due: "1 Apr",
    done: "31 Mar",
    doneTone: "teal",
    days: "3",
    daysTone: "teal",
  },
  {
    id: "approve-holdout",
    title: "Approve the change and the holdout",
    team: "Finance",
    owner: RAVI,
    accepted: "28 Mar · 4 hrs",
    acceptedTone: "teal",
    due: "30 Mar",
    done: "29 Mar",
    doneTone: "teal",
    days: "1",
    daysTone: "teal",
  },
  {
    id: "reclassify-payment-tickets",
    title: "Reclassify payment tickets",
    team: "Support",
    owner: AMARA,
    accepted: "29 Mar · 1 hr",
    acceptedTone: "teal",
    due: "5 Apr",
    done: "2 Apr",
    doneTone: "teal",
    days: "4",
    daysTone: "teal",
  },
  {
    id: "update-renewal-forecast",
    title: "Update the renewal forecast",
    team: "Customer Success",
    owner: KUNLE,
    accepted: "2 Apr · 3 hrs",
    acceptedTone: "teal",
    due: "9 Apr",
    done: "4 Apr",
    doneTone: "teal",
    days: "2",
    daysTone: "teal",
  },
];

/** H04/H05 (live) and H14 (closed) — the only two chains with a full detail build. */
export const CHAIN_DETAILS: Record<string, ChainDetail> = {
  "delivery-fee": {
    id: "delivery-fee",
    title: "The delivery-fee release",
    subtitle: "4 March to 2 August · ₦1.08B · five signals, five different names for it",
    status: "live",
    startedTeam: "Engineering",
    startedDate: "4 Mar",
    signals: [
      {
        date: "4 Mar",
        team: "Engineering",
        headline: "Shipped the delivery fee at checkout",
        detail: "Clean build, no errors, nobody watching revenue",
      },
      {
        date: "11 Mar",
        team: "Support",
        headline: '"Where is my order" became the top contact driver',
        detail: "Seen, logged, resolved, never escalated as revenue",
        tag: "the first signal",
        tagTone: "amber",
      },
      {
        date: "Apr",
        team: "Product",
        headline: "Checkout abandonment rose 3.1× at the fee step",
        detail: "Attributed to seasonality",
        tag: "the second signal",
        tagTone: "amber",
      },
      {
        date: "Jun",
        team: "Marketing",
        headline: "Second-order rate flat-lined at 27%",
        detail: "Attributed to a weak campaign",
        tag: "the third signal",
        tagTone: "amber",
      },
      {
        date: "Jul",
        team: "Customer Success",
        headline: "Renewal projection fell to 88.4%",
        detail: "Escalated · no cause found",
        tag: "the fourth signal",
        tagTone: "amber",
      },
      {
        date: "Jul",
        team: "Marketing",
        headline: "Referral rate fell for the first time in two years",
        detail: "Nobody was looking · Advocate has no owner",
        tag: "the fifth signal",
        tagTone: "rose",
      },
      {
        date: "2 Aug",
        team: "Everyone",
        headline: "Flolyt connected all five to one release",
        detail: "One room, four hours",
        tag: "the room",
        tagTone: "ultra",
      },
    ],
    liveInsights: [
      {
        tone: "ultra",
        title: "Five teams each had a piece of the answer and none of them was wrong",
        body: "Every symptom was real, every number was correct in its own tool, and every attribution was reasonable given what that team could see. The failure was that the pieces lived in five systems with five vocabularies and no shared room — and the fifth signal was invisible because that stage has never had an owner.",
      },
      {
        tone: "rose",
        title: "Support was right in seven days and it took another 144 for anybody to hear",
        body: "The earliest correct reading came from the stage with the smallest number and the least power to act on it. That is why a reclassified contact driver now opens a room automatically.",
      },
    ],
    obligationsSubtitle: "Seven obligations from one decision · six accepted · one overdue",
    obligationsStats: [
      { eyebrow: "OBLIGATIONS", value: "7", note: "from one decision" },
      { eyebrow: "ACCEPTED", value: "6 of 7", tone: "amber", note: "one has no yes" },
      { eyebrow: "OVERDUE", value: "1", tone: "rose", note: "four days" },
      { eyebrow: "MEDIAN TIME TO ACCEPT", value: "3.2 hrs", tone: "teal", note: "when accepted at all" },
    ],
    obligations: [
      {
        id: "fee-at-basket",
        chainId: "delivery-fee",
        title: "Show the fee at basket, not at checkout",
        team: "Product",
        owner: ZAINAB,
        due: "7 Aug",
        state: "shipped",
        stateTone: "teal",
        lastMoved: "7 Aug",
      },
      {
        id: "instrument-fee-shown",
        chainId: "delivery-fee",
        title: "Instrument checkout.fee_shown",
        team: "Engineering",
        owner: SAM,
        due: "14 Aug",
        state: "in progress",
        stateTone: "amber",
        lastMoved: "Yesterday",
      },
      {
        id: "hold-releases",
        chainId: "delivery-fee",
        title: "Hold releases against revenue 14 days",
        team: "Engineering",
        unacceptedLabel: "Unaccepted",
        due: "in effect",
        state: "read 4×",
        stateTone: "rose",
        lastMoved: "2 Aug",
        lastMovedTone: "rose",
      },
      {
        id: "reactivate-100k",
        chainId: "delivery-fee",
        title: "Reactivate 100,000 without a discount",
        team: "Marketing",
        owner: IFEOMA,
        due: "8 Aug",
        state: "awaiting approval",
        stateTone: "amber",
        lastMoved: "07:41",
      },
      {
        id: "retry-cards-payday",
        chainId: "delivery-fee",
        title: "Retry cards on payday",
        team: "Finance",
        owner: RAVI,
        due: "3 Aug",
        state: "approved",
        stateTone: "teal",
        lastMoved: "3 Aug",
      },
      {
        id: "reclassify-wismo",
        chainId: "delivery-fee",
        title: 'Reclassify "where is my order"',
        team: "Support",
        owner: AMARA,
        due: "done",
        state: "done",
        stateTone: "teal",
        lastMoved: "4 Aug",
      },
      {
        id: "renewal-reforecast",
        chainId: "delivery-fee",
        title: "Re-forecast the August renewal book",
        team: "Customer Success",
        owner: KUNLE,
        due: "9 Aug",
        dueTone: "rose",
        state: "4 days overdue",
        stateTone: "rose",
        lastMoved: "2 Aug",
        lastMovedTone: "rose",
      },
    ],
    obligationsInsight: {
      tone: "rose",
      title: "Two rows are the whole reason this view exists",
      body: "One obligation is four days overdue and has not moved since the day it was created. Another has been read four times and accepted by nobody — which, in every tool that is not this one, is indistinguishable from being done.",
    },
  },
  "card-retry": {
    id: "card-retry",
    title: "Card retry window",
    subtitle: "Closed 2 April · four obligations, all accepted same-day · ₦62M in nine days",
    status: "closed",
    startedTeam: "Finance",
    startedDate: "28 Mar",
    closedSummary: {
      tone: "teal",
      title: "Closed 2 April · four obligations, all accepted, all done, nine days",
      body: "₦62M recovered against a holdout. This is what a chain looks like when every obligation has a name and a date and somebody says yes on the same day.",
    },
    closedObligations: closedObligationsForCardRetry,
    closedInsights: closedInsightsForCardRetry,
    closedFooter: {
      tone: "teal",
      title: "Nine days from first signal to ₦62M recovered",
      body: 'The delivery-fee chain took 151 days to the same point. The difference is not effort or intelligence — it is that every obligation here had a name, a date and a same-day yes, and that no part of it required a decision nobody owned.',
    },
  },
};

/** H06 — only "renewal-reforecast" has a full detail build, the section's canonical demo obligation (also threaded through H09/H10/H16). */
export const OBLIGATION_DETAILS: Record<string, ObligationDetail> = {
  "renewal-reforecast": {
    id: "renewal-reforecast",
    chainId: "delivery-fee",
    chainTitle: "The delivery-fee release",
    title: "Re-forecast the August renewal book",
    team: "Customer Success",
    owner: KUNLE,
    due: "9 August",
    overdueBy: "four days",
    state: "Not started",
    stateTone: "rose",
    blocks: "₦88M",
    blocksTone: "rose",
    originTitle: "Second order never happened · closed 2 August",
    originBody:
      "The room found that the delivery-fee change reduced second orders by 11 points across 148,000 customers. The August renewal book was built in July on the old repeat rate, so it is overstated by roughly ₦88M. Re-forecasting it is not optional work — every downstream number depends on it.",
    timeline: [
      { at: "2 Aug 14:12", headline: "Created by the room", detail: "Routed to Customer Success by the stage-owner rule" },
      { at: "2 Aug 16:40", headline: "Accepted by Kunle Ade", headlineTone: "teal", detail: "Due date set to 9 Aug by Kunle" },
      { at: "6 Aug 09:02", headline: "Viewed", detail: "No change to state" },
      { at: "9 Aug 00:00", headline: "Became overdue", headlineTone: "rose", detail: "Nobody was notified · no rule covered an overdue handoff" },
      { at: "12 Aug 06:00", headline: "Appeared in Kunle's daily list", headlineTone: "ultra", detail: "Pinned, regardless of value · the new rule" },
      { at: "13 Aug 06:00", headline: "Escalated to the chain owner", headlineTone: "amber", detail: "Ada told · day 4 of the escalation ladder" },
    ],
  },
};

/** H12 — team load bars (`/handoff/load`). */
export const TEAM_LOAD = [
  { team: "Engineering" as const, total: 41, overdue: 14, median: "21 days", percent: 100, tone: "rose" as const },
  { team: "Product" as const, total: 18, overdue: 3, median: "6 days", percent: 44, tone: "amber" as const },
  { team: "Marketing" as const, total: 14, overdue: 1, median: "4 days", percent: 34, tone: "amber" as const },
  { team: "Support" as const, total: 11, overdue: 0, median: "2 days", percent: 27, tone: "teal" as const },
  { team: "Customer Success" as const, total: 9, overdue: 2, median: "11 days", percent: 27, tone: "amber" as const },
  { team: "Finance" as const, total: 4, overdue: 0, median: "1 day", percent: 22, tone: "amber" as const },
];

/** H12 — "Engineering, in detail" table. `fromChain`/`fromChainId` link back to a built chain only where one exists (Discount leakage, Lagos delivery failures, the delivery-fee release); "Loyalty tier rename" isn't one of H02's six listed chains, so it stays plain text. */
export const ENGINEERING_LOAD_DETAIL = [
  {
    id: "instrument-fee-shown",
    title: "Instrument checkout.fee_shown",
    fromChain: "The delivery-fee release",
    fromChainId: "delivery-fee",
    due: "14 Aug",
    age: "10 days",
    accepted: "Sam",
    cls: "instrumentation",
    clsTone: "amber" as const,
  },
  {
    id: "hold-releases",
    title: "Hold releases against revenue 14 days",
    fromChain: "The delivery-fee release",
    fromChainId: "delivery-fee",
    due: "in effect",
    age: "21 days",
    ageTone: "rose" as const,
    accepted: "nobody",
    acceptedTone: "rose" as const,
    cls: "process change",
    clsTone: "rose" as const,
  },
  {
    id: "instrument-tier-shown",
    title: "Instrument tier_shown",
    fromChain: "Loyalty tier rename",
    due: "2 Aug",
    dueTone: "rose" as const,
    age: "34 days",
    ageTone: "rose" as const,
    accepted: "Sam",
    cls: "instrumentation",
    clsTone: "amber" as const,
  },
  {
    id: "order-lines-feed",
    title: "Add order_lines to the feed",
    fromChain: "Discount leakage",
    fromChainId: "discount-leakage",
    due: "28 Jul",
    dueTone: "rose" as const,
    age: "41 days",
    ageTone: "rose" as const,
    accepted: "nobody",
    acceptedTone: "rose" as const,
    cls: "instrumentation",
    clsTone: "amber" as const,
  },
  {
    id: "lagos-address-autocomplete",
    title: "Fix the Lagos address autocomplete",
    fromChain: "Lagos delivery failures",
    fromChainId: "lagos-delivery-failures",
    due: "9 Aug",
    dueTone: "rose" as const,
    age: "15 days",
    ageTone: "rose" as const,
    accepted: "Sam",
    cls: "product work",
    clsTone: "neutral" as const,
  },
];

/** H11 — escalation ladder table (`/settings/handoff-escalation`). */
export const ESCALATION_LADDER = [
  { when: "2 days before due", what: "A reminder to the owner", who: "Owner only", where: "their digest", canTurnOff: "yes", canTurnOffTone: "teal" as const },
  { when: "On the due date", what: "Owner asked to confirm or re-date", who: "Owner only", where: "inbox · needs a decision", whereTone: "amber" as const, canTurnOff: "yes", canTurnOffTone: "teal" as const },
  { when: "1 day overdue", what: "The chain owner is told", who: "Owner + chain owner", where: "inbox · both", whereTone: "amber" as const, canTurnOff: "no", canTurnOffTone: "rose" as const },
  { when: "3 days overdue", what: "Enters the daily list regardless of value", who: "Owner's team lead", where: "/today · pinned", whereTone: "amber" as const, canTurnOff: "no", canTurnOffTone: "rose" as const },
  { when: "7 days overdue", what: "Escalates one level up", who: "Team lead's manager", where: "inbox · push", whereTone: "rose" as const, canTurnOff: "no", canTurnOffTone: "rose" as const },
  { when: "Never accepted, 7 days", what: "Returns to the room that created it", who: "The room", where: "/rooms/:id/plays", whereTone: "rose" as const, canTurnOff: "no", canTurnOffTone: "rose" as const },
  { when: "14 days overdue", what: "Stops · it is an org problem now", who: "Nobody new", where: "stays where it is", canTurnOff: "by design", canTurnOffTone: "neutral" as const },
];

export const ESCALATION_RULES = [
  {
    eyebrow: "RULE ONE",
    title: "An overdue obligation is never below the line",
    body: "The daily list ranks by revenue at stake. A ₦4M obligation three days overdue is pinned above a ₦40M item that is on schedule — because a broken commitment is a different kind of thing from an open opportunity.",
    footnote: "changes /today",
    footnoteTone: "amber" as const,
  },
  {
    eyebrow: "RULE TWO",
    title: "An unaccepted obligation is not a quiet one",
    body: 'Seven days with nobody having said yes returns it to the room. In every other tool, read-and-not-accepted is indistinguishable from done — which is how "hold every release against revenue" sat for eleven days.',
    footnote: "changes /handoff",
    footnoteTone: "rose" as const,
  },
  {
    eyebrow: "THE LIMIT",
    title: "Escalation stops at two levels",
    body: "It reaches a manager's manager and stops. Beyond that it is an organisational problem, not a notification problem, and more emails will not fix it.",
    footnote: "by design",
    footnoteTone: "neutral" as const,
  },
];

/** H13 — Peter Kariuki's departure handover (`/settings/departures`). */
export const DEPARTURE = {
  person: PETER,
  lastDay: "Friday 22 August",
  itemCount: 23,
  atRisk: "₦146M",
  rows: [
    { label: "Rooms he owns", count: 5, behindIt: "₦88M", behindItTone: "rose" as const, ifNothing: "unowned · they go stale", ifNothingTone: "rose" as const, goesTo: JOY, state: "chosen", stateTone: "teal" as const },
    { label: "Obligations he accepted", count: 7, behindIt: "₦31M", behindItTone: "amber" as const, ifNothing: "silently overdue", ifNothingTone: "rose" as const, goesTo: DAVID, state: "chosen", stateTone: "teal" as const },
    { label: "Approvals routed to him", count: 4, behindIt: "₦19M", behindItTone: "amber" as const, ifNothing: "they queue forever", ifNothingTone: "rose" as const, goesTo: KUNLE, state: "chosen", stateTone: "teal" as const },
    { label: "Goals he owns", count: 2, behindIt: "₦8M", ifNothing: "no owner at review", ifNothingTone: "amber" as const, goesTo: KUNLE, state: "chosen", stateTone: "teal" as const },
    { label: "A standing authority he was granted", count: 1, behindIt: "—", ifNothing: "revoked automatically", ifNothingTone: "teal" as const, goesTo: undefined, state: "revoked", stateTone: "teal" as const },
    { label: "Decisions he made", count: 41, behindIt: "—", ifNothing: "stay his, permanently", ifNothingTone: "teal" as const, goesTo: undefined, state: "kept", stateTone: "teal" as const },
    { label: "Dissent he recorded", count: 3, behindIt: "—", ifNothing: "stays his, permanently", ifNothingTone: "teal" as const, goesTo: undefined, state: "kept", stateTone: "teal" as const },
  ],
  cards: [
    {
      eyebrow: "TRANSFERS",
      title: "Everything forward-looking",
      body: "Rooms, obligations, approvals, goals. These are commitments the company made and they outlive whoever happened to be holding them.",
      footnote: "18 of 23",
      footnoteTone: "teal" as const,
    },
    {
      eyebrow: "NEVER TRANSFERS",
      title: "Everything he decided or disagreed with",
      body: "41 decisions and 3 recorded dissents stay attributed to Peter Kariuki permanently. Reassigning authorship to tidy an org chart would falsify the record.",
      footnote: "read-only, permanently",
      footnoteTone: "amber" as const,
    },
    {
      eyebrow: "REVOKED, NOT TRANSFERRED",
      title: "The standing authority",
      body: "An authority is a specific person saying they would approve a class of play. It cannot be inherited — Joy would have to be granted her own, by Ada, deliberately.",
      footnote: "expires at 18:00 Friday",
      footnoteTone: "rose" as const,
    },
  ],
};

/** H15 — how handoffs get created (`/settings/handoff`). */
export const HANDOFF_TRIGGERS = [
  { trigger: "A room decision names another team", automatic: "yes", automaticTone: "ultra" as const, goesTo: "stage owner of that team", quarter: 41, canChange: "no", canChangeTone: "rose" as const },
  { trigger: "A room needs data it does not have", automatic: "yes", automaticTone: "ultra" as const, goesTo: "the source owner", quarter: 14, canChange: "no", canChangeTone: "rose" as const },
  { trigger: "A play is blocked by another team's work", automatic: "yes", automaticTone: "ultra" as const, goesTo: "that team's lead", quarter: 9, canChange: "no", canChangeTone: "rose" as const },
  { trigger: "A room closes with something outstanding", automatic: "yes", automaticTone: "ultra" as const, goesTo: "whoever it names", quarter: 18, canChange: "no", canChangeTone: "rose" as const },
  { trigger: "Somebody types one", automatic: "no", automaticTone: "neutral" as const, goesTo: "whoever they pick", quarter: 3, canChange: "always available", canChangeTone: "teal" as const },
  { trigger: "An agent decides one is needed", automatic: "never", automaticTone: "rose" as const, goesTo: "—", quarter: 0, canChange: "by design", canChangeTone: "neutral" as const },
];

export const HANDOFF_CARRIES = [
  { label: "The room that created it", value: "and the decision, and the evidence behind it" },
  { label: "A named owner", value: "never a team alone · a team cannot accept anything", tone: "amber" as const },
  { label: "A date", value: "set by whoever accepts it, not by whoever created it", tone: "teal" as const },
  { label: "A state", value: "not started, in progress, done, disputed, overdue" },
  { label: "What it blocks", value: "so its priority is legible without opening the room" },
  { label: "Its full history", value: "including a previous owner who did not do it", tone: "amber" as const },
];

/** H08 — drafted from "Second order never happened"'s decision doc, opened from that room's Decision tab. */
export const DECISION_DRAFTED_OBLIGATIONS = [
  { id: "instrument-fee-shown", title: "Instrument checkout.fee_shown", team: "Engineering" as const, due: "14 Aug" },
  { id: "fee-at-basket", title: "Show the fee at basket, not checkout", team: "Product" as const, due: "7 Aug" },
  { id: "renewal-reforecast", title: "Re-forecast the August renewal book", team: "Customer Success" as const, due: "9 Aug" },
  { id: "hold-releases", title: "Hold every release against revenue 14 days", team: "Engineering" as const, due: "in effect" },
];
